[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "anthropic>=0.54.0",
    "arabic-reshaper>=3.0.0",
    "asgiref>=3.8.1",
    "asyncpg>=0.30.0",
    "bcrypt>=4.3.0",
    "beautifulsoup4>=4.13.4",
    "email-validator>=2.2.0",
    "fastapi>=0.115.13",
    "flask-dance>=7.1.0",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn[gthread,uvicorn]>=23.0.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "locust>=2.37.10",
    "openai>=1.90.0",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "pyjwt>=2.10.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-cov>=6.2.1",
    "python-bidi>=0.6.6",
    "python-multipart>=0.0.20",
    "selenium>=4.33.0",
    "sqlalchemy>=2.0.41",
    "uvicorn[standard]>=0.34.3",
    "flask-login>=0.6.3",
    "oauthlib>=3.3.1",
    "werkzeug>=3.1.3",
]
