# Replit configuration for Arabic Voice of Customer Platform
run = "gunicorn --bind 0.0.0.0:5000 --reuse-port --reload main:app"
language = "python3"
modules = ["python-3.11"]

# Environment variables for deployment
[env]
PYTHONPATH = "."
PYTHON_VERSION = "3.11"

# Deployment configuration
[deployment]
run = ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 main:app"]
deploymentTarget = "cloudrun"
ignorePorts = false

# Build configuration to avoid UV issues
[nix]
channel = "stable-24.05"

# Package configuration
[packager]
language = "python3"
installDir = "packages"
ignoredPaths = [".git", "__pycache__", "tests", ".pytest_cache"]

[packager.features]
enabledForHosting = false
packageSearch = true
guessImports = true

# Python-specific configuration
[languages.python3]
pattern = "**/*.py"

[languages.python3.languageServer]
start = "pylsp"

# Gitignore patterns
[gitHubImport]
requiredFiles = [".replit", "replit.nix"]

# Development configuration
[interpreter]
command = ["python", "main.py"]