name: Arabic VoC CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Basic Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask sqlalchemy gunicorn pytest
        
    - name: Basic syntax check
      run: |
        python -m py_compile app.py
        python -m py_compile main.py
        
    - name: Test imports
      run: |
        python -c "from app import app; print('Flask app imports successfully')"
        
    - name: Check static files
      run: |
        ls -la static/css/
        ls -la templates/